# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tokenisation/byte_pair_encoding_from_scratch.ipynb.

# %% auto #0
__all__ = ["BPE"]


# %% ../../nbs/tokenisation/byte_pair_encoding_from_scratch.ipynb #29c4bdf1
class BPE:
    def __init__(self, vocab_size: int):
        self.special_tokens = ["<UNK>", "<PAD>", "<BOS>", "<EOS>"]
        self.vocab = []

    def train(self, text: str, vocab_size: int):
        pass

    def encode(self, text: str):
        pass

    def decode(self, tokens: list[int]):
        pass
