# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tokenisation/sentencepiece.ipynb.

# %% auto #0
__all__ = ["SentencePieceBPE"]


# %% ../../nbs/tokenisation/sentencepiece.ipynb #a417f704
class SentencePieceBPE:
    def __init__(self, vocab_size: int):
        self.vocab: dict[int, bytes] = {i: bytes([i]) for i in range(256)}
        self.merges: dict[tuple[int, int], int] = {}
        self.vocab_size = vocab_size
        self.space_token = "\u2581"

    def encode(self, text: str) -> list[int]:
        tokens = self.get_tokens(text)
        for pair, idx in self.merges.items():
            tokens = self.merge_pair(tokens, pair, idx)
        return tokens

    def decode(self, tokens: list[int]) -> str:
        token_bytes: bytes = b"".join(self.vocab[token] for token in tokens)
        text = token_bytes.decode("utf-8", errors="replace")
        text = text.replace(self.space_token, " ").strip()
        return text

    def train(self, text: str):
        tokens = self.get_tokens(text)
        for i in range(256, self.vocab_size):
            pair_counts = self.get_pair_counts(tokens)
            most_common_pair = max(pair_counts, key=lambda p: pair_counts[p])
            tokens = self.merge_pair(tokens, most_common_pair, i)
            self.merges[most_common_pair] = i
            self.vocab[i] = self.vocab[most_common_pair[0]] + self.vocab[most_common_pair[1]]

    def get_tokens(self, text: str) -> list[int]:
        text = f" {text}"
        text = text.replace(" ", self.space_token)
        tokens: bytes = text.encode(encoding="utf-8")
        return list(map(int, tokens))

    def get_pair_counts(self, tokens: list[int]) -> dict[tuple[int, int], int]:
        counts: dict[tuple[int, int], int] = {}
        for pair in zip(tokens, tokens[1:]):
            counts[pair] = counts.get(pair, 0) + 1
        return counts

    def merge_pair(self, tokens: list[int], pair: tuple[int, int], idx: int) -> list[int]:
        new_tokens = []
        i = 0
        while i < len(tokens):
            if i < len(tokens) - 1 and (tokens[i], tokens[i + 1]) == pair:
                new_tokens.append(idx)
                i += 2
            else:
                new_tokens.append(tokens[i])
                i += 1
        return new_tokens
