[project]
name = "ai-notes"
version = "0.1.0"
description = "Code and visualizations for understanding transformer architectures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.3.0",
    "numpy>=2.0.0",
    "matplotlib>=3.9.0",
    "torch>=2.5.0",
    "lorem>=0.1.1",
    "ruff",
    "tqdm",
    "ty"
]

[tool.ruff]
line-length = 119
lint.ignore = ["F401"]
