# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'ai_notes'},
  'syms': { 'ai_notes.core': {'ai_notes.core.foo': ('core.html#foo', 'ai_notes/core.py')},
            'ai_notes.tokenisation.bpe': { 'ai_notes.tokenisation.bpe.BPE': ( 'tokenisation/byte_pair_encoding_from_scratch.html#bpe',
                                                                              'ai_notes/tokenisation/bpe.py'),
                                           'ai_notes.tokenisation.bpe.BPE.__init__': ( 'tokenisation/byte_pair_encoding_from_scratch.html#bpe.__init__',
                                                                                       'ai_notes/tokenisation/bpe.py'),
                                           'ai_notes.tokenisation.bpe.BPE.decode': ( 'tokenisation/byte_pair_encoding_from_scratch.html#bpe.decode',
                                                                                     'ai_notes/tokenisation/bpe.py'),
                                           'ai_notes.tokenisation.bpe.BPE.encode': ( 'tokenisation/byte_pair_encoding_from_scratch.html#bpe.encode',
                                                                                     'ai_notes/tokenisation/bpe.py'),
                                           'ai_notes.tokenisation.bpe.BPE.train': ( 'tokenisation/byte_pair_encoding_from_scratch.html#bpe.train',
                                                                                    'ai_notes/tokenisation/bpe.py')}}}
